#!/usr/bin/env python3
"""Generate src/data/pokemon/species_by_bst.h -- species sorted by base stat total.

BST is a static property, so the sorted index the BST-similarity randomizer needs can live
in ROM instead of being rebuilt in EWRAM at boot. Two tables mirror the two species pools
the randomizer already keeps (with and without legendaries).

Re-run this if base stats or either species pool changes:
    python3 tools/randomizer/gen_bst_table.py
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
STATS = ('baseHP', 'baseAttack', 'baseDefense', 'baseSpeed', 'baseSpAttack', 'baseSpDefense')


def parse_bst():
    """species name -> base stat total, using the default (new) stat values."""
    src = open(os.path.join(ROOT, 'src/data/pokemon/species_info.h')).read()
    parts = re.split(r'\n    \[(SPECIES_[A-Z0-9_]+)\]\s*=', src)
    bst = {}
    for i in range(1, len(parts), 2):
        sp, body = parts[i], parts[i + 1]
        vals = []
        for k in STATS:
            # first match is the live value; *_old variants follow it
            m = re.search(r'\.' + k + r'\s*=\s*(\d+)', body)
            vals.append(int(m.group(1)) if m else None)
        if all(v is not None for v in vals) and sp not in bst:
            bst[sp] = sum(vals)
    return bst


def parse_pool(name):
    src = open(os.path.join(ROOT, 'src/pokemon.c')).read()
    m = re.search(r'static const u16 ' + name + r'\[\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not m:
        sys.exit('could not find %s in src/pokemon.c' % name)
    seen, out = set(), []
    for s in re.findall(r'^\s*(SPECIES_[A-Z0-9_]+)\s*,', m.group(1), re.M):
        if s != 'SPECIES_NONE' and s not in seen:
            seen.add(s)
            out.append(s)
    return out


def emit(f, table_name, species, bst):
    ranked = sorted(((s, bst[s]) for s in species if s in bst), key=lambda x: (x[1], x[0]))
    f.write('#define %s_COUNT %d\n' % (table_name.upper(), len(ranked)))
    f.write('static const u16 %s[] =\n{\n' % table_name)
    for s, v in ranked:
        f.write('    %-28s // %d\n' % (s + ',', v))
    f.write('};\n\n')
    return ranked


def main():
    bst = parse_bst()
    normal = parse_pool('sRandomSpecies')
    legend = parse_pool('sRandomSpeciesLegendary')

    out = os.path.join(ROOT, 'src/data/pokemon/species_by_bst.h')
    with open(out, 'w') as f:
        f.write('// Generated by tools/randomizer/gen_bst_table.py -- do not edit by hand.\n')
        f.write('// Species sorted ascending by base stat total, for BST-similarity randomization.\n')
        f.write('// Sorted order is load-bearing: the lookup binary-searches these.\n\n')
        a = emit(f, 'sSpeciesByBST', normal, bst)
        b = emit(f, 'sSpeciesByBSTLegendary', legend, bst)

    dropped = [s for s in normal if s not in bst]
    print('wrote %s' % out)
    print('  sSpeciesByBST           %d entries  (BST %d..%d)' % (len(a), a[0][1], a[-1][1]))
    print('  sSpeciesByBSTLegendary  %d entries  (BST %d..%d)' % (len(b), b[0][1], b[-1][1]))
    if dropped:
        print('  skipped (no base stats parsed): %d -- %s' % (len(dropped), ', '.join(dropped[:6])))


if __name__ == '__main__':
    main()
