#!/usr/bin/env python3
"""Generate src/data/pokemon/species_family_root.h.

Maps every species to the root of its evolution family, so the ability randomizers can seed on
something that does not change when a Pokemon evolves. Walking the chain at runtime is not an
option: GetPreEvolution scans the whole evolution table, and GetAbilityBySpecies runs per frame
in battle.
"""
import os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')) + '/'

species_h = open(ROOT + 'include/constants/species.h').read()
ids = {m.group(1): int(m.group(2))
       for m in re.finditer(r'#define\s+(SPECIES_[A-Z0-9_]+)\s+(\d+)', species_h)}
num_species = ids['SPECIES_EGG']            # NUM_SPECIES

evo = open(ROOT + 'src/data/pokemon/evolution.h').read()
# Entries run from one "[SPECIES_X] =" to the next, and a split family spans several lines, so
# the body is taken as everything up to the following entry rather than to the first brace.
parent = {}                                  # child -> parent
starts = [(m.start(), m.group(1)) for m in re.finditer(r'\[(SPECIES_[A-Z0-9_]+)\]\s*=', evo)]
for k, (pos, src) in enumerate(starts):
    end = starts[k + 1][0] if k + 1 < len(starts) else len(evo)
    for target in re.findall(r'\{\s*EVO_\w+\s*,\s*[^,]+,\s*(SPECIES_[A-Z0-9_]+)\s*\}', evo[pos:end]):
        parent.setdefault(target, src)       # first listed parent wins for split families

def root_of(name):
    seen = set()
    while name in parent and name not in seen:
        seen.add(name)
        name = parent[name]
    return name

by_id = {v: k for k, v in ids.items() if v < num_species}
lines = []
for i in range(num_species):
    name = by_id.get(i)
    if name is None or name not in ids:
        lines.append('    [%d] = %d,' % (i, i))
        continue
    lines.append('    [%s] = %s,' % (name, root_of(name)))

out = ['// Generated by tools/randomizer/gen_family_root.py -- do not edit by hand.',
       '//',
       '// Root of each species\' evolution family. Seeding the ability randomizers on this rather',
       '// than on the current species keeps a Pokemon\'s ability when it evolves: Bagon, Shelgon and',
       '// Salamence all resolve to Bagon and therefore to one ability.',
       '//',
       '// A split family (Wurmple, Eevee, Tyrogue) resolves every branch to the shared base, so the',
       '// branches share an ability too.',
       '',
       'static const u16 sSpeciesFamilyRoot[NUM_SPECIES] =',
       '{'] + lines + ['};', '']
open(ROOT + 'src/data/pokemon/species_family_root.h', 'w').write('\n'.join(out))

changed = sum(1 for n in ids if n in parent)
print('wrote %d entries; %d species have a parent' % (num_species, changed))
for probe in ('SPECIES_SALAMENCE', 'SPECIES_SHELGON', 'SPECIES_BAGON',
              'SPECIES_SILCOON', 'SPECIES_BEAUTIFLY', 'SPECIES_VAPOREON'):
    if probe in ids:
        print('   %-20s -> %s' % (probe, root_of(probe)))
